# Generated by Django 5.2.8 on 2025-11-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_rename_cpd_funcionarios_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelManagers(
            name='funcionarios',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Remuneração'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='sobrenome',
            field=models.CharField(max_length=255, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='tempo_de_servico',
            field=models.IntegerField(default=0, verbose_name='Tempo de Serviço (anos)'),
        ),
    ]
